spring.application.name=Mini_Digital_Banking_system
server.port=8083

spring.datasource.url = jdbc:oracle:thin:@//localhost:1521/xepdb1
spring.datasource.username = king
spring.datasource.password = king123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl.auto= validate

spring.jpa.show-sql=true


jwt.secret=jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_FOR_JWT_SECURITY_2026
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ignitex94@gmail.com
spring.mail.password=youswmikhptlebqs

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true