--CREATING THE USERS TABLE TO STORE USERS BIODATA

CREATE TABLE USERS(
user_id SERIAL PRIMARY KEY,
 first_name VARCHAR(50) NOT NULL,
 last_name VARCHAR(50) NOT NULL,
 full_name VARCHAR(100) GENERATED ALWAYS AS (first_name || ' ' || last_name),
 email VARCHAR(100) UNIQUE NOT NULL,
 phone_number  VARCHAR(50) NOT NULL,
 bvn VARCHAR(50) UNIQUE NOT NULL,
 user_password VARCHAR(50) NOT NULL,
 user_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 user_modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 NIN_num VARCHAR(50) UNIQUE NOT NULL
); 

SELECT *
FROM USERS;

--CREATING THE ACCOUNT TABLE TO STORE THE ACCOUNT INFORMATION OF GIVEN USERS

CREATE TABLE ACCOUNT(
	account_id SERIAL PRIMARY KEY,
	user_id INT NOT NULL REFERENCES USERS(user_id) ON DELETE CASCADE,
	account_number VARCHAR(50) UNIQUE NOT NULL,
	balance DECIMAL(15,2) DEFAULT 0.00 CHECK (balance>=0),
	account_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT *
FROM ACCOUNT;

--CREATING THE TRANSACTIONS TABLE THAT WOULD STORE ALL KINDS OF TRANSACTIONS(WITHDRAWALS, DEPOSITS, TRANSFER)

CREATE TABLE TRANSACTION(
	transaction_id SERIAL PRIMARY KEY,
	sender_account_id INT REFERENCES ACCOUNT(account_id) ON DELETE SET NULL,
	receiver_account_id INT  REFERENCES ACCOUNT(account_id) ON DELETE SET NULL,
	transaction_type VARCHAR(50) NOT NULL,
	amount DECIMAL(15,2) NOT NULL CHECK(amount>0),
	status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
	description VARCHAR(150),
	transaction_created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

SELECT *
FROM TRANSACTION;

--3 STORED PROCEDURES NEEDED FOR THE TASK
-- DEPOSIT_MONEY() : IT'LL UPDATE THE BALANCE IN THE ACCOUNT TABLE
					--AND INSERT A ROW IN THE TRANSACTIONS TABLE AS A DEPOSIT

					
--WITHDRAW() : CHECKS BALANCE{ IF LESS THAN, PRINT 'INSUFFICIENT FUNDS', 
				-- UPDATE THE BALANCE IN THE ACCOUNT TABLE
				--AND INSERT A ROW IN THE TRANSACTIONS TABLE AS A WITHDRAWAL

				
--TRANSFER(): CONFIRMS THE RECEIVER'S ACCOUNT EXISTS
			--CONFIRMS SUFFICIENT BALANCE IN SENDER'S ACCOUNT
			--UPDATE THE BALANCE IN THE ACCOUNT TABLE FOR BOTH PARTIES
			--AND INSERT A ROW IN THE TRANSACTIONS TABLE AS A TRANSFER